services:
  # flask server
  web:
    build: .
    container_name: flask_app
    ports:
      - "5001:5000"  
    volumes:
      - ./app:/app/app            
      - ./.env:/app/.env
      - ./utils:/app/utils
    environment:
      - REDIS_URL=redis://redis:6379/0
      - OLLAMA_BASE_URL=http://host.docker.internal:11434  # able to access host.docker.internal from container
      - CHROMA_DB_HOST=chromadb 
      - CHROMA_DB_PORT=8000
      - PYTHONUNBUFFERED=1  # disable buffering
    extra_hosts:
      - "host.docker.internal:host-gateway"  # allow container to access host services
    depends_on:
      - redis
      - chromadb
    restart: always

  # redis
  redis:
    image: redis/redis-stack:latest
    container_name: redis_service
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
    restart: always

  # chromadb
  chromadb:
    image: chromadb/chroma:latest
    container_name: chroma_service
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
    restart: always

volumes:
  redis_data:
  chroma_data: